steps:
  - if: build.tag =~ /^seed/
    name: ":debian: build seed deb"
    env:
        VERSION_TAG: $BUILDKITE_TAG
    commands:
      - "git tag $BUILDKITE_TAG"
      - ".buildkite/scripts/make_deb.sh seed"
    key: "seed-deb"
    artifact_paths: "*.deb"
    agents:
      queue: "erlang"

  - if: build.tag =~ /^testnet_seed/
    name: ":debian: build testnet seed deb"
    env:
        VERSION_TAG: $BUILDKITE_TAG
    commands:
      - "git tag $BUILDKITE_TAG"
      - ".buildkite/scripts/make_deb.sh testnet_seed"
    key: "testnet-seed-deb"
    artifact_paths: "*.deb"
    agents:
      queue: "erlang"

  - if: build.tag =~ /^devnet_seed/
    name: ":debian: build seed deb"
    env:
        VERSION_TAG: $BUILDKITE_TAG
    commands:
      - "git tag $BUILDKITE_TAG"
      - ".buildkite/scripts/make_deb.sh devnet_seed"
    key: "devnet-seed-deb"
    artifact_paths: "*.deb"
    agents:
      queue: "erlang"

  - if: build.tag =~ /^seed/
    name: ":cloud: upload seed deb to packagecloud"
    env:
      VERSION_TAG: $BUILDKITE_TAG
    commands:
      - ".buildkite/scripts/packagecloud_upload.sh seed"
    depends_on: "seed-deb"
    agents:
      queue: "erlang"

  - if: build.tag =~ /^testnet_seed/
    name: ":cloud: upload testnet seed deb to packagecloud"
    env:
      VERSION_TAG: $BUILDKITE_TAG
    commands:
      - ".buildkite/scripts/packagecloud_upload.sh testnet_seed"
    depends_on: "testnet-seed-deb"
    agents:
      queue: "erlang"

  - if: build.tag =~ /^testnet_seed/
    name: ":cloud: upload devnet seed deb to packagecloud"
    env:
      VERSION_TAG: $BUILDKITE_TAG
    commands:
      - ".buildkite/scripts/packagecloud_upload.sh devnet_seed"
    depends_on: "devnet-seed-deb"
    agents:
      queue: "erlang"


